### ISSUE TITLE
qc output bad json file

### ISSUE THREAD

**Issue by Lizhen0909** [tobiasrausch/alfred#10]
qc may generate bad json file [bad.json.gz](https://github.com/tobiasrausch/alfred/files/2781248/bad.json.gz)

Both v0.1.16 and v0.1.15 are tried.

**Comment by tobiasrausch** [comment]
Thanks for reporting this bug. In rare cases alfred reports -nan values which should be 'null' according to the JSON specification. We are working on this. For the time being jq is able to correct these errors:

`zcat bad.json.gz | jq "." | gzip -c > fixed.json.gz`

fixed.json.gz then works at [https://gear.embl.de/alfred/](https://gear.embl.de/alfred/)

**Comment by Lizhen0909** [comment]
Thanks.

**Comment by tobiasrausch** [comment]
Fixed in [v0.1.17](https://github.com/tobiasrausch/alfred/releases/tag/v0.1.17).
