### ISSUE TITLE
can't install alfred

### ISSUE THREAD

**Issue by slhogle** [tobiasrausch/alfred#13]
Hi, I'm interested in using your tool but I can't install it.

Here's my environment:
```
rpm -qf /etc/redhat-release
centos-release-6-10.el6.centos.12.3.x86_64
```

```
uname -s -r
Linux 2.6.32-642.15.1.el6.x86_64
````

when trying to run precompiled executable I get:
```
FATAL: kernel too old
[1]    15238 abort (core dumped)  ./alfred_v0.1.17_linux_x86_64bit
```

I can install from bioconda no problem. when I try to run I get:

```
alfred
alfred: symbol lookup error: alfred: undefined symbol: _ZN5boost15program_options3argE
(miniconda3-latest)
```

Tried compiling from source wtih gcc/5.4.0, intelmpi/5.1.3, boost/1.6.3, and cmake/3.9.0 but get a lot of errors - mostly having to do with boost (see attached error log).

Any ideas as to what's going wrong?

[error.log](https://github.com/tobiasrausch/alfred/files/2997356/error.log)

cheers,
-shane

**Comment by slhogle** [comment]
Update: Alfred v0.1.7 precompiled binaries work and so does installing from source. No releases higher than v0.1.7 work for me.

so whatever changes were made between version Alfred v0.1.7 Alfred v0.1.8 is what is causing it to break on my system.

thanks,
-shane

**Comment by tobiasrausch** [comment]
Hi Shane,

If your kernel is too old for the static binaries and also Bioconda is not working then I suspect some packages on your system are really outdated. Probably best if you try the alfred docker container then: https://hub.docker.com/r/trausch/alfred/

Best, Tobias

**Comment by slhogle** [comment]
OK thanks - I was trying to get it working without Docker, but I'll give it a try. I'm still surprised this doesn't compile on our cluster...

**Comment by slhogle** [comment]
UPDATE: the docker file works but it's not ideal for our purposes. I'll close this issue
