### ISSUE TITLE
Insert size discordant with samtools

### ISSUE THREAD

**Issue by kpjonsson** [tobiasrausch/alfred#14]
For the same aligned FASTQ pair from WGS, I get a mean insert size of 362 from `samtools stats`. From `alfred qc` I get a median insert size of 65535, and actually ,all but a handful of readpairs are assigned this insert size according to the output from `zgrep ^IS`.  

I can't really figure out what's going on. Any clues?

**Comment by tobiasrausch** [comment]
I am not fully familiar with samtools stats but could it be that samtools stats only estimates the insert size from properly aligned pairs? If most of your pairs have a huge insert size (>65535bp) then samtools stats probably excludes these. Alfred is exhaustive in that sense it counts every single pair but pairs with an insert size >65535 are counted in the last bucket.

**Comment by kpjonsson** [comment]
Thanks for the reply. You seem to be correct that it's a matter of which read pairs are counted, specifically, `samtools stats` does not by default report insert sizes above 8,000, according to the documentation. From GATK CollectInsertSizeMetrics I get median insert size 345, and it says in the documentationt that this is only from read pairs mapped on the same chromosome.

Overall, the distribution below 10,000 looks similar for samtools and alfred
![image](https://user-images.githubusercontent.com/4834443/55515128-c6cca080-5637-11e9-93d8-6bdd5b0aa520.png)

What is your reasoning for looking at all read pairs?

**Comment by tobiasrausch** [comment]
Well, we use Alfred most frequently for QC purposes and for that purpose we definitely want to see if the majority of read pairs have an insert >65535bp because that usually indicates a severe problem with the sample, the library prep or the sequencing. In addition, mate-pair libraries often have median insert sizes >5kbp so trimming at 8,000bp makes little sense to me.

**Comment by kpjonsson** [comment]
@tobiasrausch I see, that makes sense. Thanks for the feedback.
