### ISSUE TITLE
ase and split not working

### ISSUE THREAD

**Issue by aziouez25** [tobiasrausch/alfred#15]
Hi,

Using a multi-sample phased vcf file with eagle2 and even the 1KG phased VCF or a toy VCF. The bam file passed the QC.

Both VCF and BAM are from RNA-seq. split did not give any error but no read was split

Thanks
A

**Comment by tobiasrausch** [comment]
I am sorry for my late reply. I have created an example script that shows how you can use the 1kGP VCF file to split a BAM file and annotate allele-specific counts.

[https://github.com/tobiasrausch/alfred/blob/master/example/split_ase_example.sh](https://github.com/tobiasrausch/alfred/blob/master/example/split_ase_example.sh)

Maybe the chromosome naming is different in the VCF and the BAM (chr1 vs. 1)?

**Comment by aziouez25** [comment]
Hi Tobias,

Thanks for your feedback. I ran the script you shared and it still does not work. The output file looks like:
chr	pos	id	ref	alt	depth	refsupport	altsupport	gt	af	pvalue
chr22	20010565	.	G	A	0	0	0	0|1	NA	NA
chr22	20023327	.	G	A	0	0	0	0|1	NA	NA
chr22	20034442	.	C	T	0	0	0	1|0	NA	NA
chr22	20037873	.	G	A	0	0	0	0|1	NA	NA
chr22	20038684	.	G	A	0	0	0	1|0	NA	NA
chr22	20038929	.	T	G	0	0	0	1|0	NA	NA
chr22	20039002	.	A	G	0	0	0	1|0	NA	NA
chr22	20039394	.	T	C	0	0	0	1|0	NA	NA
chr22	20041737	.	T	C	0	0	0	1|0	NA	NA
chr22	20042355	.	T	C	0	0	0	1|0	NA	NA
chr22	20044141	.	G	A	0	0	0	1|0	NA	NA

All the refsupport and altsupport are set to 0
Thanks
Best
A

**Comment by aziouez25** [comment]
My bad! the download had a problem. I will let you know once I try it on my data.

Thanks
best
A
