### ISSUE TITLE
feature request: multithreaded option for `alfred qc`

### ISSUE THREAD

**Issue by evanbiederstedt** [tobiasrausch/alfred#16]
Hi Tobias

Thanks for the excellent tool!

I have a very brave request: we've been included `Alfred` in our pipelines, which has proved invaluable. Recently we've noticed that `alfred qc` takes a great deal of time for high coverage WGS BAMs. Based on what I've gathered from the source code: 

https://github.com/tobiasrausch/alfred/blob/master/src/qc.h

there is no multithreaded option for `alfred qc`. 

How difficult would it be to implement this? 

Thanks, Evan

**Comment by tobiasrausch** [comment]
Hi Evan,

The main issue for high-coverage BAMs is that Alfred is exhaustive, it evaluates every single mapped read of the BAM file. For high-coverage data that's usually not necessary. We do plan to have a subsample option at some point in the future but for the time being you can use samtools for that. For instance, to evaluate only 10% of the BAM (303 is a random seed value for samtools) you can use:

`samtools view -b -s 303.10 input.bam > subsample.bam`

You can then use subsample.bam with alfred qc.

**Comment by evanbiederstedt** [comment]
Hi Tobias

**Comment by tobiasrausch** [comment]
alfred qc is mainly bounded by I/O. The actual computations are rather light-weight, it's mainly a matter of reading the millions of BAM records and unpacking the sequence information. I guess it's the same for `samtools stats` and that's why multi-threading makes little sense.

**Comment by evanbiederstedt** [comment]
Hi @tobiasrausch 

> alfred qc is mainly bounded by I/O. The actual computations are rather light-weight, it's mainly a matter of reading the millions of BAM records and unpacking the sequence information.

Right, this makes a good deal of sense. 

In order to make this multithreaded (and I say this with a great deal of naïveté, as I haven't thought this through---but I'm fascinated), one would have to split up the BAM, and then use each worker thread to read through the records therein and unpack the sequence information. Afterwards, this information would need to be merged. Is there a step I haven't considered as to why this could not work?

Thanks, Evan

**Comment by tobiasrausch** [comment]
Indeed, one could junk the BAM but that's increasing the I/O burden so only a parallel filesystem would yield a large speed-up.

**Comment by evanbiederstedt** [comment]
> so only a parallel filesystem would yield a large speed-up.

Good point.
