### ISSUE TITLE
Possible to get consensus sequence for whole bacterial genome?

### ISSUE THREAD

**Issue by BCArg** [tobiasrausch/alfred#19]
Hi Tobias, 

is it possible to get the consensus sequence for a whole bacterial genome (5498578 bp - https://www.ncbi.nlm.nih.gov/nuccore/BA000007)?

when I run `/alfred consensus -f bam -t ont ../ref494_aligned.sorted.bam`

I get 

```
[2019-Jul-10 11:57:01] alfred consensus -f bam -t ont ../ref494_aligned.sorted.bam                       │
Input format: bam                                                                                        │
Sequencing type: ont                                                                                     │
Alignment scoring (match: 3, mismatch: -2, gapopen: -3, gapext: -1)                                      │
Window: 250                                                                                              │
Position needs to be in the format chr:pos
```

Thanks in advance and best regards

**Comment by tobiasrausch** [comment]
The consensus sequence computation is for a local assembly so you need to specify a chromosome and position. With long reads one could write a bash script that computes a consensus sequence every ~1000bp but alfred has no module yet to merge these consensus sequences afterwards. Alfred just fetches all reads overlapping a given alignment position and then runs a sensitive multiple-sequence alignment and consensus computation.
