### ISSUE TITLE
make: *** [.boost] Error 1

### ISSUE THREAD

**Issue by crazyhottommy** [tobiasrausch/alfred#2]
Hi,
I got this error when installing:

```bash 
make all
cd src/modular-boost && ./bootstrap.sh --prefix=/scratch/genomic_med/apps/alfred/src/modular-boost --without-icu --with-libraries=iostreams,filesystem,system,program_options,date_time && ./b2 && ./b2 headers && cd ../../ && touch .boost
./bootstrap.sh: line 196: ./tools/build/src/engine/build.sh: No such file or directory
Building Boost.Build engine with toolset ... 
Failed to build Boost.Build build engine
Consult 'bootstrap.log' for more details
make: *** [.boost] Error 1
```
Thanks!
Tommy

**Comment by tobiasrausch** [comment]
Hi,

Did you do a recursive checkout? Looks like the Boost sources are incomplete. You can do:

cd alfred/
git submodule update --init --recursive
make all

If that still doesn't work some dependencies of Boost might be missing. Please note that there are statically compiled binaries available here: 

https://github.com/tobiasrausch/alfred/releases

These should work on most Linux distributions.

Best, Tobias

**Comment by RxLoutre** [comment]
I had the same error, unless it was htslib instead of boost.

Your solutions actually solved my issue and I was able to launch alfred !

**Comment by tobiasrausch** [comment]
Great, thanks for letting me know. I will close this issue then for the time being but please re-open if you still face problems in compiling alfred.

**Comment by user1415** [comment]
Hi.. will you plz help me ?
I got error when installing this
F:\Boost\boost_1_72_0>bootstrap.bat
Building Boost.Build engine
File Not Found

Failed to build Boost.Build engine.
Please consult bootstrap.log for further diagnostics.

'cmd' is not recognized as an internal or external command,
operable program or batch file.

**Comment by tobiasrausch** [comment]
What operating system are you using?
