### ISSUE TITLE
Repeated value for Y-axis tick labels for some plots

### ISSUE THREAD

**Issue by BCArg** [tobiasrausch/alfred#20]
Dear all, 

I have used alfred to produce QC plots from ONT sequencing and I noticed that some plots (e.g. Base Content Distribution, Read Length Distribution) all have zero's on the Y-axis tick labels. I though this could be an issue, for instance, with my local R installation, which generates the plots. Though I have noticed that the plots that come with the installation on the `example` folder (`stats.tsv.gz.pdf) also have only zero's or one's for some plots (e.g. Base Content Distribution and InDel Homopolymer Context)

**Comment by tobiasrausch** [comment]
I suppose the web application [gear.embl.de/alfred](https://gear.embl.de/alfred/) is fine? I indeed also did run into this issue previously with R Statistics and I think it's related to the scales package.

**Comment by BCArg** [comment]
Yes I have uploaded the `ecoli.json.gz` sample file and the y-axis tick labels are OK.
