### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by xf78** [tobiasrausch/alfred#21]
i install alfred use comman "make all",and i account an compilation error like below:

lboost_system -lboost_program_options -lboost_date_time -L/Analysis/biosoft/02.RNA_Soft/alfred/src/htslib/ -L/Analysis/biosoft/02.RNA_Soft/alfred/src/htslib//lib -lpthread -lhts -lz -llzma -lbz2 -Wl,-rpath,/Analysis/biosoft/02.RNA_Soft/alfred/src/htslib/
In file included from src/alfred.cpp:50:0:
src/count_rna.h:27:44: fatal error: boost/icl/split_interval_map.hpp: No such file or directory
 #include <boost/icl/split_interval_map.hpp>
                                            ^
compilation terminated.
make: *** [src/alfred] Error 1

Is it possible that the installation package I downloaded is incomplete,or my system problem ,thanks!

**Comment by tobiasrausch** [comment]
That looks like an outdated boost version. You can try updating boost or what might be easier you can also get alfred on [bioconda](https://anaconda.org/bioconda/alfred), as a [static binary](https://github.com/tobiasrausch/alfred/releases) or as a [docker container](https://hub.docker.com/r/trausch/alfred)

**Comment by Colorstorm** [comment]
Hello, 

I installed alfred via Bioconda  `conda install -c bioconda alfred`
Now I'm getting always an symbol lookup errror
`alfred: symbol lookup error: alfred: undefined symbol: _ZN5boost15program_options3argE`

What could I do to fix it?

Regards 
Fabian

**Comment by tobiasrausch** [comment]
Probably a dependency issue if that's an existing bioconda environment. I have added a test directory to alfred, [https://github.com/tobiasrausch/alfred/tree/master/test](https://github.com/tobiasrausch/alfred/tree/master/test) that includes a Makefile which downloads miniconda, adds the bioconda channel and then installs alfred. This worked for me. Can you please try if a clean bioconda installation works for you? Thanks.

**Comment by Colorstorm** [comment]
I tried to install it in an empty/new conda env and I tried your make file.
Both time came the error again. 
Here is the error after running your make file
```
alfred: symbol lookup error: alfred: undefined symbol: _ZN5boost15program_options3argE
Makefile:19: recipe for target '.test' failed
make: *** [.test] Error 127
```

**Comment by tobiasrausch** [comment]
I am sorry, I cannot reproduce this error. I tried different Ubuntu and CentOS versions but it always works with bioconda. What is your OS? You could also try using the previous build using an older boost version:

`conda install alfred=0.1.17=he089337_1`

Alternatively, I also provide [static binaries](https://github.com/tobiasrausch/alfred/releases) for alfred.

**Comment by Colorstorm** [comment]
My OS is Ubuntu 16.04.6 LTS 
But the previous build works just fine, thanks a lot.

**Comment by tobiasrausch** [comment]
Thanks, good that it is working now.
