### ISSUE TITLE
Update BioConda recipe for using Python 3.7+

### ISSUE THREAD

**Issue by lucventurini** [tobiasrausch/alfred#24]
Dear @tobiasrausch ,

many thanks for developing your package. I just wanted to note that the current Conda package only supports python below 3.7. This unnecessarily leaves out environments created with the two most recent Python versions. It is not a huge problem (thanks to the statically linked binaries) but it would be nice to update the recipe.

Kind regards

**Comment by tobiasrausch** [comment]
I am not sure I can help with this, seems to be related to the BioConda package manager. Alfred doesn't require python and as you noted, you can also install the tool using static binaries, singularity or docker containers.
