### ISSUE TITLE
error rate in stat

### ISSUE THREAD

**Issue by aspitaleri** [tobiasrausch/alfred#25]
Hi there
the error rate reported in the statistics is "The sequencing error rates are calculated over all aligned bases" as explained in the FAQ https://www.gear-genomics.com/docs/alfred/faq/#calculation-of-indel-rates-and-sequencing-error-rate.
Is that the absolute error or the percentage error rate already? I mean 0.08 is 0.08% error rate or it is 8% (0.08 on 1).
Thanks

**Comment by tobiasrausch** [comment]
It's an error rate in [0,1] and thus, 0.08 corresponds to 8%.
