### ISSUE TITLE
consensus command

### ISSUE THREAD

**Issue by ALFLAG** [tobiasrausch/alfred#26]
Hello,

I'm sorry, but I'm not sure I understand what the consensus command does...  Because when I tried, it takes one genome position and return a sequence of different lengt depending of the genome location.
Does it take all the reads aligned in one position, and then generate a consensus sequence of all the group of reads ?

I'm a virologist and I'm looking for a new tool (different from bcftools) that generate consensus sequence of a complete genome (and in my case less than one hundred thousand nucleotide), does alfred help me with that ?
Thank a lot.

Alexandre

**Comment by tobiasrausch** [comment]
> Does it take all the reads aligned in one position, and then generate a consensus sequence of all the group of reads ?

Yes, it builds a multiple-sequence-alignment and then generates a consensus sequence from that. It's indeed for a "local" reference-guided assembly.

**Comment by ALFLAG** [comment]
OK. Thank you for your answer.

Is there any possibility for adding an option that generate consensus sequence over the entire genome using the same process?

**Comment by tobiasrausch** [comment]
One could write a script that computes the consensus every ~250bp (depends on your read length) and then merges these consensus sequences. Not trivial but that could be an option.
