### ISSUE TITLE
[Question] Calculation of indel rate

### ISSUE THREAD

**Issue by RxLoutre** [tobiasrausch/alfred#3]
Hi Tobias,

In the output of albert, when using .metrics.tsv file, there is an insertion and deletion rate.

But I'm wondering how exactly this score means and how it is calculated. Is it a score per base ? Is it calculated overall the sequence and with the reads coverage ?

Thanks in advance for your answers !

Cheers,

Roxane

**Comment by tobiasrausch** [comment]
Hi Roxane,

It is indeed calculated over all aligned bases. It is the total number of deletions (Cigar D, deletion size is irrelevant) divided by the total number of aligned bases (Cigar M, matches and mismatches are counted as aligned). For insertions, it is the total number of insertions (Cigar I).

Best, Tobias
