### ISSUE TITLE
Discorcondant value from Alfred's #SoftClippedBases and CIGAR string's S

### ISSUE THREAD

**Issue by juheon** [tobiasrausch/alfred#32]
Hi,

I am using alfred version 0.2.1 to qc my RNA-seq data using the following command (alfred qc -r <hg38.fa> -b <target_gene> -o test.alfred.out.gz test.bam)
My test.bam file contains only one read pair for test purposes as described below. In the bam file, CIGAR string of read1 of readpair_11405287 is 10S65M and that of read2 is 32M1216N43M.
I expect to have 10 as #SoftClippedBases but alfred outputted 1 as #SoftClippedBases. Does "#SoftClippedBases" represent the number of reads containing any size of soft-clipped bases rather than the size of soft-clipped bases?

test.bam
`readpair_11405287       99      chr17   36486687        255     **10S65M**  =       36493975        8579    GAAACAGTCTCTCCCACAAAACCATGGCGTCGCTCAAATGTAGCACCGTCGTCTGCGTGATCTGCTTGGAGAAGC     F~~a~~~~~~~~~~G~~~~~G~^~~~y~~~~~o~~~~t~~~~w~~~\~~~~~~~~~~~~~~~~~~~C~H~~~~~~     NH:i:1  HI:i:1  AS:i:137        nM:i:1  NM:i:1
readpair_11405287      147     chr17   36493975        255     **32M1216N43M**     =       36486687        -8579   CAGAGTTTCTTTGCAGAATTTAAAGAATTTAGGGGAATCTGCAACATTAAGAAGCTTATTGCTCAATCCACACCT     ~~~~R~~g~~~r~~~~~~~~s~~e~~e~~V~~~~Z~}~~~~~~~~~~~~}~~~~}~~~~}~~~~~~a~S~~~~i~     NH:i:1  HI:i:1  AS:i:137        nM:i:1  NM:i:0`

alfred qc output
`Sample	test
Library	DefaultLib
#QCFail	0
QCFailFraction	0
#DuplicateMarked	0
DuplicateFraction	0
#Unmapped	0
UnmappedFraction	0
#Mapped	2
MappedFraction	1
#MappedRead1	1
#MappedRead2	1
RatioMapped2vsMapped1	1
#MappedForward	1
MappedForwardFraction	0.5
#MappedReverse	1
MappedReverseFraction	0.5
#SecondaryAlignments	0
SecondaryAlignmentFraction	0
#SupplementaryAlignments	0
SupplementaryAlignmentFraction	0
#SplicedAlignments	1
SplicedAlignmentFraction	0.5
#Pairs	1
#MappedPairs	1
MappedPairsFraction	1
#MappedSameChr	1
MappedSameChrFraction	1
#MappedProperPair	1
MappedProperFraction	1
#ReferenceBp	83257441
#ReferenceNs	337237
#AlignedBases	140
#MatchedBases	139
MatchRate	0.992857
#MismatchedBases	1
MismatchRate	0.00714286
#DeletionsCigarD	0
DeletionRate	0
HomopolymerContextDel	0
#InsertionsCigarI	0
InsertionRate	0
HomopolymerContextIns	0
**#SoftClippedBases	1**
SoftClipRate	0.00714286
#HardClippedBases	0
HardClipRate	0
ErrorRate	0.0142857
MedianReadLength	0:0
DefaultLibraryLayout	2
MedianInsertSize	0
MedianCoverage	0
SDCoverage	0.918795
CoveredBp	140
FractionCovered	1.68837e-06
BpCov1ToCovNRatio	1
BpCov1ToCov2Ratio	inf
MedianMAPQ	255
#TotalBedBp	7959
#AlignedBasesInBed	140
FractionInBed	1
EnrichmentOverBed	10418.4`

**Comment by tobiasrausch** [comment]
Good point, that's mislabelled. I just changed this to #SoftClippedCigarS and #HardClippedCigarH then it also fits to CigarI and CigarD for insertions and deletions. As you already concluded, Alfred counts the occurrences of CigarS independent of the size of soft-clipped bases.

**Comment by juheon** [comment]
I appreciate your clarification. Thanks!
