### ISSUE TITLE
 installation error

### ISSUE THREAD

**Issue by Saddamhus** [tobiasrausch/alfred#36]
Hello, I have installed Alfred from bioconda but when I run the following command I am seeing this error. Could you please tell me how can I resolve it? Thank you in advance.

I am on OSX Catalina and have tried brew update and brew upgrade as it worked for others with similar issue.  

```

saddams-MBP:~ saddamhusain$ alfred
dyld: Library not loaded: @rpath/libboost_iostreams.dylib
  Referenced from: /Users/saddamhusain/opt/anaconda2/pkgs/alfred-0.2.1-h098d73b_1/bin/alfred
  Reason: image not found
Abort trap: 6

```

**Comment by tobiasrausch** [comment]
Looks like a problem in your conda environment.

`which alfred`

shoud probably point to

`/Users/saddamhusain/opt/anaconda2/bin/alfred`

and the libraries are then usually in

`ls /Users/saddamhusain/opt/anaconda2/lib/libboost_iostreams.dylib `

**Comment by Saddamhus** [comment]
Thank you for the response, yes files are the way you pointed above. Where should they supposed to be? I am fairly new to data analysis, please don't mind to my silly questions.
