### ISSUE TITLE
Fail to open index

### ISSUE THREAD

**Issue by Saddamhus** [tobiasrausch/alfred#37]
Hello,  I am trying to generate BAM quality control file recently but it is failing with this error. I am assuming -r option is asking for reference genome fasta file that I have downloaded from UCSC. The bam file is generated from bowtie alignment.

```
saddams-MBP:alfred saddamhusain$ ls
S4_L_.fastq	S4_L_bwt.bam	hg38.1.ebwt	hg38.2.ebwt	hg38.3.ebwt	hg38.4.ebwt	hg38.fa		hg38.fa.fai	hg38.rev.1.ebwt	hg38.rev.2.ebwt
saddams-MBP:alfred saddamhusain$ alfred qc -r hg38.fa -o qc.tsv.gz S4_L_bwt.bam
Fail to open index for S4_L_bwt.bam
saddams-MBP:alfred saddamhusain$

```

**Comment by tobiasrausch** [comment]
BAM files need to be indexed.

`samtools index S4_L_bwt.bam`
