### ISSUE TITLE
Something wrong with on-target rate calculation?

### ISSUE THREAD

**Issue by epioneMW** [tobiasrausch/alfred#4]
Hi, I was trying to use alfred on WES. Seems the on-target rate calculation is much lower than the result I get from other tools. And also in the InsertSize plot, what does it mean for "Insert size > 27701 (8.61%)" ? Can insert size be so large?

**Comment by tobiasrausch** [comment]
The insert size plot is meant to show the majority of the data so one can check if the insert size distribution is Gaussian-like. The header states how many pairs are not shown and that number is quite disturbing in your case. Almost 10% of the read-pairs with an insert size > 27Kbp suggests to me some library prep problem. What is the mapping rate and the mapped fraction on the same chromosome that Alfred reports?

**Comment by epioneMW** [comment]
Thanks for your reply. I used the same bed file. And the insert size plot from another tool seems normal. Could there be something wrong with alfred?

**Comment by tobiasrausch** [comment]
Does the other tool show all read-pair orientations? If the BAM file can be shared I can take a look if you want.

**Comment by tobiasrausch** [comment]
I don't think I can help without a BAM file so I will close this issue for the time being. Feel free to reopen if you have more information on this issue.
