### ISSUE TITLE
SDCoverage

### ISSUE THREAD

**Issue by jeffinrockey** [tobiasrausch/alfred#40]
Hi,
Would you please provide a link or detail on the output values of alfred qc.
Especially "SDCoverage"
Jeffin

**Comment by tobiasrausch** [comment]
SDCoverage is a standardized measure of coverage variability. This can be useful to compare how pronounced peaks are in ATAC-Seq or ChIP-Seq. It can also be useful to compare the uniformity of coverage in WGS experiments.

**Comment by jeffinrockey** [comment]
Thanks. 
Closing.
