### ISSUE TITLE
Question: Are duplicated reads counted for ErrorRate?

### ISSUE THREAD

**Issue by FrankFeng** [tobiasrausch/alfred#41]
I asked this question, because I noticed that duplicated reads are NOT counted for `MappedFraction`, as `MappedFraction + UnmappedFraction < 1` when `DuplicateFraction > 0`.

Thanks!

**Comment by tobiasrausch** [comment]
Total read counts are #QCFail + #DuplicateMarked + #Unmapped + #Mapped. The fractions simply use total read counts as denominator.

**Comment by FrankFeng** [comment]
According to your FAQ, the sequencing error rates are calculated over all **aligned bases**. Are duplicated reads included in those "**aligned bases**"?

Thanks!

**Comment by tobiasrausch** [comment]
No. Duplicate reads, secondary alignments and supplementary alignments are not included for seq. error rates.
