### ISSUE TITLE
Chromosome mapping with `--bed` option

### ISSUE THREAD

**Issue by anoronh4** [tobiasrausch/alfred#43]
Great comprehensive tool! I was just wondering if certain statistics such as `ObsExpRatio` in Chromosome Mapping takes into consideration the lengths of the regions in the bed file that is provided with the option `--bed` .  in otherwords, is the expected part of the ratio based on the full length of the genome, or just based on the regions in the bed.

**Comment by tobiasrausch** [comment]
The mapping statistics by chromosome do not take into account a bed file. The BED file is only used for on-target and coverage per target distributions and the GC content.

**Comment by anoronh4** [comment]
thanks for that information. I guess we can get similar info by chromosome out of the lines that start with `^TC`. however it would be nice if that were a built-in feature of `alfred`, because it seems that `^CM` lines are not that informative when you use a target file. just a suggestion.

**Comment by anoronh4** [comment]
additional quick question: what is the `Extension` metric in the OnTarget table of Alfred? i couldn't find any explanation in the `alfred` documentation.

**Comment by tobiasrausch** [comment]
Exactly, alfred extends the target regions by `extension` bases and then re-evaluates the number of reads in a target region. That's useful because target enrichment techniques often involve capture probes and these probes might capture fragments that extend beyond the core probe (target) region.
