### ISSUE TITLE
Question: are supplementary and duplicated alignments excluded for the "FractionInBed"?

### ISSUE THREAD

**Issue by FrankFeng** [tobiasrausch/alfred#46]
Hi,

When running `alfred qc` with the default parameters and with a bed file provided, are supplementary and duplicated alignments excluded for the calculation of `FractionInBed`? 

Thanks!
Frank

**Comment by tobiasrausch** [comment]
Yes, these alignments are excluded. Alfred only counts the numbers of supplementary and duplicated alignments using the default options but these alignments are not used for other statistics (GC content, match/mismatch counts, coverage, ...).
