### ISSUE TITLE
Error in Rscript

### ISSUE THREAD

**Issue by alanmejiamaza** [tobiasrausch/alfred#55]
Hi,

Thank you for bringing this excellent tool.

I was trying to plot the qc.tsv.gz file but it keeps giving errors. This is the output I obtained:
WARNING: ignoring environment value of R_HOME
[1] "Base Content"
Error: Must request at least one colour from a hue palette.
Execution halted

**Comment by tobiasrausch** [comment]
Looks like some kind of R problem. Maybe easier to upload the output json file here:

[https://www.gear-genomics.com/alfred/(https://www.gear-genomics.com/alfred/)

The graphs are the same as in the Rscript but the website is interactive.
