### ISSUE TITLE
hard clipping stats

### ISSUE THREAD

**Issue by danessel** [tobiasrausch/alfred#6]
Hard clipping stats present in BAM file are not summerized

**Comment by tobiasrausch** [comment]
Should be present in the summary table?

`zgrep ^ME qc.tsv.gz | datamash transpose | grep "HardClip"`

**Comment by danessel** [comment]
scaffold380     2048    chr01   1       60      394161H487M1I38M182I55M1I40M1I180M1D206M52D839M7I52M1D232M58D939M33D566M1D13M1I8M1D51M1D238M60I1433M56D10M1D16M1I216M1D182M1D278M73I1021M1D21M2I2M3D75M1D2M1D9M2I16M1I57M1I40M23D140M1D2M3I7M2D23M2I3M2D73M1I127M1I493M56D854M75D32M2D1824M51D91M2I5M1D3M1D88M1I5M3D644M1D454M1D577M1I4M1D85M1D550M1I347M42D741M5D18M1I267M71D173M6D69M3D34M1I119M1D322M5D247M362I287M709966H 

the bam file was generated with Minimap2, but the summery says:
#HardClippedBases
0
HardClipRate
0

**Comment by tobiasrausch** [comment]
Ah I see, thanks for posting this SAM record. Alfred counts this read as a secondary alignment but then only takes the primary alignment forward to compute error rates, mapping statistics, and so on. That's probably the desired method for illumina data but I agree for long reads that's not ideal. I have added now a flag to alfred qc (-s) to evaluate secondary alignments. 

`alfred qc -s -r ref.fa ...`

**Comment by tobiasrausch** [comment]
Do you need a new static binary or are you working from the github source?

**Comment by danessel** [comment]
I downloaded the static binary, didn't use the source yet

**Comment by tobiasrausch** [comment]
Okay, no problem. Here is a new [static binary](https://github.com/tobiasrausch/alfred/releases/tag/v0.1.9).

**Comment by danessel** [comment]
thanks a lot but:
the -s flag gives: 
[2018-Aug-24 09:56:51] BAM file parsing

0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***Segmentation fault
but without -s the script works fine

**Comment by tobiasrausch** [comment]
Thanks. It looks like some aligners set the sequence and quality character strings for secondary alignments to '*' and this indeed caused a segfault in alfred. I fixed this now because '*' for the sequence and quality is allowed by the SAM spec. What is a bit unfortunate is that some aligners then don't use the new BAM_CEQUAL ('=') and BAM_CDIFF ('X') CIGAR characters which would help to estimate the mismatch and match rate but well, it is what it is. I hope this is working now with most long read aligners but please let me know if you still have problems. I also added -u to evaluate supplementary alignments. For long reads you might want to evaluate both, secondary and supplementary alignments:

`./src/alfred qc -su -r <genome.fa> <input.bam>`



 because that would make it easier to estimate the match and mismatch rate but I tried to find

>                                  else if (op == '=') op = BAM_CEQUAL;
>                                  else if (op == 'X') op = BAM_CDIFF;

// Evaluate secondary alignments                                      
          // Sequence and quality strings might be '*' for secondary alignments
,

**Comment by tobiasrausch** [comment]
Here is the update release [alfred v0.1.10](https://github.com/tobiasrausch/alfred/releases/tag/v0.1.10)

**Comment by danessel** [comment]
Thanks, it does what it should do !

**Comment by danessel** [comment]
I noticed that alfred summaries of hardclipped/softclipped bases are a bit different then expected (much lower values over a complete bamfile. I took 2 lines and analyzed the results:
scaffold380     2048    chr01   1       60           394161H487M1I38M182I55M1I40M1I180M1D206M52D839M7I52M1D232M58D939M33D566M1D13M1I8M1D51M1D238M60I1433M56D10M1D16M1I216M1D182M1D278M73I1021M1D21M2I2M3D75M1D2M1D9M2I16M1I57M1I40M23D140M1D2M3I7M2D23M2I3M2D73M1I127M1I493M56D854M75D32M2D1824M51D91M2I5M1D3M1D88M1I5M3D644M1D454M1D577M1I4M1D85M1D550M1I347M42D741M5D18M1I267M71D173M6D69M3D34M1I119M1D322M5D247M362I287M709966H487M1I38M182I55M1I40M1I180M1D206M52D839M7I52M1D232M58D939M33D566M1D13M1I8M1D51M1D238M60I1433M56D10M1D16M1I216M1D182M1D278M73I1021M1D21M2I2M3D75M1D2M1D9M2I16M1I57M1I40M23D140M1D2M3I7M2D23M2I3M2D73M1I127M1I493M56D854M75D32M2D1824M51D91M2I5M1D3M1D88M1I5M3D644M1D454M1D577M1I4M1D85M1D550M1I347M42D741M5D18M1I267M71D173M6D69M3D34M1I119M1D322M5D247M362I287M709966H
scaffold4441    16      chr01   12746   1       217S107M1D5M1I17M1I95M1D104M1D123M60S 

alfred will give HardClipped = 2 SoftClipped=0, but sum 394161H + 709966H = 1.104.127 hardclipped bases and 217S + 60S = 277 softclipped bases

Any ideas about this ? Maybe Alferd is not useful for Minimap2 based bamfiles due to the CIGAR characters, or is alfred using some filtering on the bam file ?

**Comment by danessel** [comment]
too quick with my comment, the sequence length of scaffold380 is just 16740bp so Minimap2 CIGAR is a bit different then expected ;-)

**Comment by danessel** [comment]
sorry, forgot that the hardclipped bases are not in the bamfile

**Comment by tobiasrausch** [comment]
Alfred counts the events per read not the length of these events. For instance, for RNA-Seq it counts the number of splicing events but not the length. The same is true for deletions and insertions, it counts the number of D and I events and then separately the InDel size distribution. For sequencing error rate estimations this was more reliable and comparable across technologies and sequencing assays.

**Comment by danessel** [comment]
Ah, that clarifies it, thanks a lot
