### ISSUE TITLE
consensus command

### ISSUE THREAD

**Issue by migrau** [tobiasrausch/alfred#7]
Hi, 
Is the `consensus` command available in the last version? 

```
[]$ ./alfred_v0.1.12_linux_x86_64bit consensus
Unrecognized command consensus
```

Thanks!

**Comment by tobiasrausch** [comment]
Hi,

I added the consensus feature very recently. Here is a new static binary release: [https://github.com/tobiasrausch/alfred/releases](https://github.com/tobiasrausch/alfred/releases)

Please let me know if you also need an updated bioconda version.

Best, Tobias
