### ISSUE TITLE
MedianMAPQ

### ISSUE THREAD

**Issue by zhixue** [tobiasrausch/alfred#70]
Hi,
thank you for your useful work!

I am confused with **MedianMAPQ** in output.   
It is the median of **all records' MAPQ of reads** or **all primary records' MAPQ of reads**?

I have several bam files of ONT and all of them have MedianMAPQ=60.

**Comment by tobiasrausch** [comment]
That's not unusual. Some mappers like bwa mem for illumina data or minimap2 for ONT indeed tend to map the majority of primary alignments at good mapping quality. You can simply view the BAM file yourself, the MAPQ field is column 5.

**Comment by zhixue** [comment]
Thank you for your help. I have solved the problem.
