### ISSUE TITLE
A question of the example shell of the Haplotype-specific

### ISSUE THREAD

**Issue by MMengrui** [tobiasrausch/alfred#71]
Hi Tobias
I have a question of the example shell in the software folder.
![企业微信截图_16418016297093](https://user-images.githubusercontent.com/49903097/148733972-df097191-5cab-4900-8021-db77ebca5870.png)
When you convert the vcf file to the bcf format, you use the parameter (-m2 -M2 -c 1 -C 1) to filter some variant sites.
It seemed that this parameter would retain the variant sites of 0/1 type. Why you use this parameter?

**Comment by tobiasrausch** [comment]
When you want to split the data by haplotype only heterozygous variants (0/1) are informative for a diploid sample.

**Comment by MMengrui** [comment]
I got it. Thank you very much!
