### ISSUE TITLE
On-target coverage BED file

### ISSUE THREAD

**Issue by lautty** [tobiasrausch/alfred#8]
Hi there, I'm trying to use Alfred to look at on-target statistics, but I can't figure out the correct BED format expected by the tool. At the very minimum I have my BED file of targets with the three required fields (chrom, chromStart, chromEnd). Is any additional information required? 
Alfred will still run and generate an output, but none of the on-target statistics are present (i.e., the following columns in the tsv are lacking leading me to believe there's a problem with parsing the BED file).

#TotalBedBp | #AlignedBasesInBed | FractionInBed | EnrichmentOverBed
-- | -- | -- | --
0 | 0 | 0 | -nan

**Comment by tobiasrausch** [comment]
Can you try to gzip your bed file before running alfred? 

`gzip input.bed`

I think in the last release there was a bug with the detection of gzipped vs. non-gzipped files. It's fixed already in the latest github code.

**Comment by tobiasrausch** [comment]
I just verified that the latest code accepts both gzip bed files and plain bed files. Please let me know if you need a new release.

**Comment by tobiasrausch** [comment]
Thanks for getting back to us.
