### ISSUE TITLE
Alignment metrics

### ISSUE THREAD

**Issue by sarah872** [tobiasrausch/alfred#9]
I am using `albert` for evaluating Oxford Nanopore reads, and it serves my purpose very well, thanks! I have a question concerning the alignment metrics from the file `qc.tsv.gz`. Could you explain some of the stats? I am particularly interested how you calculate the `ErrorRate`.
Best!

**Comment by sarah872** [comment]
Thanks, so last question: This takes into account the reference sequence, and not only the phred score in the fastq file (that comes from the sequencing)?

**Comment by tobiasrausch** [comment]
The calculated error rates are completely independent from the phred score in the FASTQ file. The error rates are only based on the alignment of reads and with respect to the reference sequence.
