### ISSUE TITLE
Are supplementary reads included in majority of stats

### ISSUE THREAD

**Issue by rob234king** [tobiasrausch/alfred#90]
are supplementary reads and secondary used for match rate, coverage etc. You would need to filter for primary reads to get information for just primary mappings?

**Comment by tobiasrausch** [comment]
By default, only primary alignments are used. With `-u` supplementary alignments are also taken into account (useful for long reads) and `-s` activates secondary alignments.

**Comment by rob234king** [comment]
when I don't use -us then I still get reported secondary alignments and supplementary alignments, the rest of the stats change. for one of my bams the supplementary goes down to 1.3% but secondary still high. Another bam it is unchanged with the reported SupplementaryAlignmentFraction and SecondaryAlignmentFraction quite high but the other numbers do change. Is it expected that these stats don't change but the other numbers to change?

**Comment by tobiasrausch** [comment]
The read counts should be independent of `-u` and `-s` but for GC content, matches, mismatches, etc. supplementary / secondary alignments are either included or excluded.

[https://github.com/tobiasrausch/alfred/blob/main/src/bamstats.h#L356-L375](https://github.com/tobiasrausch/alfred/blob/main/src/bamstats.h#L356-L375)
