### ISSUE TITLE
Insert size histogram

### ISSUE THREAD

**Issue by graceooh** [tobiasrausch/alfred#91]
Hello, 

I am having some difficulty interpreting the insert size histogram and couldn't find documentation that explains this plot in depth. What does "R+ pairs" mean and could you clarify this plot in general? 
Also, how should this histogram look like with good library preparation and for it to work with Delly? (I ran this tool because I ran into the warning "non-default paired-end layout").  

Thank you very much!

**Comment by tobiasrausch** [comment]
R+ is the default illumina paired-end orientation. A good whole-genome library shows a peak between 400-600bp and >95% (ideally >99%) should be R+. You can browse examples at [https://www.gear-genomics.com/alfred/](https://www.gear-genomics.com/alfred/). Just pick `DNA-Seq, Whole-genome, Paired-end` under Reference data sets.

**Comment by graceooh** [comment]
@tobiasrausch Thank you for your comment! I'm assuming R+ is referring to FR then? Could you clarify what R-, F+ and F- means?

**Comment by tobiasrausch** [comment]
R+:     --R1-->  <--R2---
R-:     <--R1--   ---R2--->
F+:     ---R1-->    --R2--->
F-:     <--R1---   <---R2---

**Comment by graceooh** [comment]
Great, thank you very much! :)
