### ISSUE TITLE
How ErrorRate is calculated?

### ISSUE THREAD

**Issue by FrankFeng2022** [tobiasrausch/alfred#92]
Hi,

Thanks for creating such a useful tool!

I have referred to the FAQ, but am still not sure how ErrorRate is calculated. Is ErrorRate equal to the total number of **_mismatches_** divided by the total number of aligned bases? 

Regards,
Frank

**Comment by tobiasrausch** [comment]
Hi Frank,

Issues #3, #6 and #9 already provide an answer to this question I believe.

Best, Tobias

**Comment by FrankFeng2022** [comment]
Thanks, Tobias! Unfortunately, it doesn't answer my question :-(  

Those issue pages and the FAQ only describe how INDEL rate is calculated, with using the Cigar **D** and **I**. It is still not clear with the **_ErrorRate_** . To be specific, do you use edit distance (e.g. the NM tag) for the calculation of ErrorRate? 

Regards,
Frank

**Comment by tobiasrausch** [comment]
The ErrorRate uses Cigar D and I and mismatches, normalized over all aligned bases.

**Comment by FrankFeng2022** [comment]
The Cigar M represents either matches or mismatches. For instance, only with a Cigar string **10M2D30M**, we don't know how many bases are matched or mismatched. 

How can Alfred know the number of mismatched bases? Sorry, but this is still unclear to me.

**Comment by tobiasrausch** [comment]
Cigar M is compared to the reference sequence and then it's clear whether it's a match or mismatch.
